ProjectWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('services/', include('services.urls')),
    path('blogs/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('authentication/', include('authentication.urls')),
    path('', include('ProjectWebApp.urls')),
    path('orders/', include('orders.urls')),
]

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.blog, name="Blog"),
    path('category/<int:category_id>/', views.category, name="category"),
]

cart/urls.py
from django.urls import path

from . import views

app_name="cart"

urlpatterns = [
    path('add/<int:product_id>/', views.add_product, name="add"),
    path('delete/<int:product_id>/', views.delete_product, name="delete"),
    path('reduce/<int:product_id>/', views.reduce_product, name="reduce"),
    path('clean/', views.clear_cart, name="clear"),
]

shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.shop, name="Tienda"),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models

# Create your models here.

class ProdCategory(models.Model):
    name=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="prodCategory"
        verbose_name_plural="prodCategories"

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=50)
    categories=models.ForeignKey(ProdCategory, on_delete=models.CASCADE)
    image=models.ImageField(upload_to="shop", null=True, blank=True)
    price=models.FloatField()
    stock=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="product"
        verbose_name_plural="products"

cart/views.py
from django.shortcuts import render, redirect

from .cart import Cart

from shop.models import Product


# Create your views here.

def add_product(request, product_id):

    cart=Cart(request)
    
    product=Product.objects.get(id=product_id)

    cart.add(product=product)

    return redirect("Tienda")

def delete_product(request, product_id):

    cart=Cart(request)
    
    product=Product.objects.get(id=product_id)

    cart.delete(product=product)

    return redirect("Tienda")

def reduce_product(request, product_id):

    cart=Cart(request)
    
    product=Product.objects.get(id=product_id)

    cart.reduce(product=product)

    return redirect("Tienda")

def clear_cart(request, product_id):

    cart=Cart(request)
    
    cart.clear_cart()

    return redirect("Tienda")

shop/views.py
from django.shortcuts import render
from .models import Product

# Create your views here.

def shop(request):
    products=Product.objects.all()

    return render(request, "shop/shop.html", {"products":products})

shop/templates/cart/widget.html
<table class="table table-bordered" style="color: white;">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro compras
            </th>
        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.cart.items %}
            {% for key, value in request.session.cart.items %}
                <tr class="text-center">
                    <td>{{value.name}}</td>
                    <td>{{value.amount}}</td>
                    <td>

                        <a href="{% url 'cart:add' value.product_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'cart:reduce' value.product_id %}" class="btn btn-sm btn-success">-</a><br/>
                        
                        {{value.price}} $

                    </td>
                </tr>

            {% endfor %}
        {%else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>
        {% endif %}

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{cart_total_amount}} $
            </td>
        </tr>
        
        {% if request.session.cart.items %}

        <tr>
            <td colspan="3" style="text-align: center;">
                <a href="#" class="btn btn-success">Comprar</a>
            </td>
        </tr>
        
        {% endif %}


    </tfoot>
</table>